### ISSUE TITLE
Breaks on paths with spaces

### ISSUE THREAD

**Issue by WashuHakubi** [jpetrie/fetch-dependency#7]
This error message does not include the Result which means you miss relevant error information:
https://github.com/jpetrie/fetch-dependency/blob/fd99ce54be186684211703bff5763653a77cc249/FetchDependency.cmake#L16

Because the `${CMAKE_COMMAND}`, `${ConfigureDirectory}`  and `${BuildDirectory}` are not quoted these commands fail if any of the paths contain spaces.
https://github.com/jpetrie/fetch-dependency/blob/fd99ce54be186684211703bff5763653a77cc249/FetchDependency.cmake#L82-L83
https://github.com/jpetrie/fetch-dependency/blob/fd99ce54be186684211703bff5763653a77cc249/FetchDependency.cmake#L115

**Comment by jpetrie** [comment]
Fixed by #8.
